#!/bin/bash

DIR=$(dirname $0)
HOME=$(cd $DIR/..; pwd)

echo "DIR: $DIR"
echo "HOME: $HOME"
echo "PWD: $PWD"

CLASSPATH=
for f in $(ls $HOME/lib); do
  CLASSPATH=$HOME/lib/$f:$CLASSPATH
done

java -cp $CLASSPATH -Dhome=$HOME com.inversoft.mybatis.generator.Main "$@"